name: "GitFlow: Finish Hotfix (PR-based)"
description: "Create PRs from hotfix into main & devel instead of merging directly."

inputs:
  hotfix_branch:
    description: "Hotfix branch, e.g. hotfix/1.3.1"
    required: true

  version:
    description: "Version number for display only"
    required: true

  main_branch:
    description: "Main branch name"
    required: false
    default: "main"

  develop_branch:
    description: "Develop branch name"
    required: false
    default: "devel"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: cli/cli@v2.83.1

    - name: Authenticate gh
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: echo "Authenticated"

    - name: PR hotfix → main
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr create \
          --base "${{ inputs.main_branch }}" \
          --head "${{ inputs.hotfix_branch }}" \
          --title "Hotfix ${{ inputs.version }} → ${{ inputs.main_branch }}" \
          --body "Automated PR to merge hotfix ${{ inputs.version }} into ${{ inputs.main_branch }}."

    - name: PR hotfix → develop
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr create \
          --base "${{ inputs.develop_branch }}" \
          --head "${{ inputs.hotfix_branch }}" \
          --title "Hotfix ${{ inputs.version }} → ${{ inputs.develop_branch }}" \
          --body "Automated PR to merge hotfix ${{ inputs.version }} into ${{ inputs.develop_branch }}."
